#pragma once

#include <cstdint>

enum class SizeType
{
    Fixed,
    MDependent,
    XDependent
};

struct OpCodeInfo
{
    const char* mnemonic;
    const char* addressing_mode;
    SizeType size_type;
    u8 size_when_set;
    u8 size_when_clear;
};

constexpr OpCodeInfo ricoh_5a22_opcode_info[256] = {
    /* 0x00 */ { "BRK", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x01 */ { "ORA", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0x02 */ { "COP", "Immediate", SizeType::Fixed, 2, 2 },
    /* 0x03 */ { "ORA", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0x04 */ { "TSB", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x05 */ { "ORA", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x06 */ { "ASL", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x07 */ { "ORA", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0x08 */ { "PHP", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x09 */ { "ORA", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0x0A */ { "ASL", "Accumulator", SizeType::Fixed, 1, 1 },
    /* 0x0B */ { "PHD", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x0C */ { "TSB", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x0D */ { "ORA", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x0E */ { "ASL", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x0F */ { "ORA", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x10 */ { "BPL", "Relative", SizeType::Fixed, 2, 2 },
    /* 0x11 */ { "ORA", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x12 */ { "ORA", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0x13 */ { "ORA", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x14 */ { "TRB", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x15 */ { "ORA", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x16 */ { "ASL", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x17 */ { "ORA", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x18 */ { "CLC", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x19 */ { "ORA", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0x1A */ { "INC", "Accumulator", SizeType::Fixed, 1, 1 },
    /* 0x1B */ { "TCS", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x1C */ { "TRB", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x1D */ { "ORA", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x1E */ { "ASL", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x1F */ { "ORA", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0x20 */ { "JSR", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x21 */ { "AND", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0x22 */ { "JSL", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x23 */ { "AND", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0x24 */ { "BIT", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x25 */ { "AND", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x26 */ { "ROL", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x27 */ { "AND", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0x28 */ { "PLP", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x29 */ { "AND", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0x2A */ { "ROL", "Accumulator", SizeType::Fixed, 1, 1 },
    /* 0x2B */ { "PLD", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x2C */ { "BIT", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x2D */ { "AND", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x2E */ { "ROL", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x2F */ { "AND", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x30 */ { "BMI", "Relative", SizeType::Fixed, 2, 2 },
    /* 0x31 */ { "AND", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x32 */ { "AND", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0x33 */ { "AND", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x34 */ { "BIT", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x35 */ { "AND", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x36 */ { "ROL", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x37 */ { "AND", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x38 */ { "SEC", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x39 */ { "AND", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0x3A */ { "DEC", "Accumulator", SizeType::Fixed, 1, 1 },
    /* 0x3B */ { "TSC", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x3C */ { "BIT", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x3D */ { "AND", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x3E */ { "ROL", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x3F */ { "AND", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0x40 */ { "RTI", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x41 */ { "EOR", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0x42 */ { "WDM", "Immediate", SizeType::Fixed, 2, 2 },
    /* 0x43 */ { "EOR", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0x44 */ { "MVP", "Block Move", SizeType::Fixed, 3, 3 },
    /* 0x45 */ { "EOR", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x46 */ { "LSR", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x47 */ { "EOR", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0x48 */ { "PHA", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x49 */ { "EOR", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0x4A */ { "LSR", "Accumulator", SizeType::Fixed, 1, 1 },
    /* 0x4B */ { "PHK", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x4C */ { "JMP", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x4D */ { "EOR", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x4E */ { "LSR", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x4F */ { "EOR", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x50 */ { "BVC", "Relative", SizeType::Fixed, 2, 2 },
    /* 0x51 */ { "EOR", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x52 */ { "EOR", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0x53 */ { "EOR", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x54 */ { "MVN", "Block Move", SizeType::Fixed, 3, 3 },
    /* 0x55 */ { "EOR", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x56 */ { "LSR", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x57 */ { "EOR", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x58 */ { "CLI", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x59 */ { "EOR", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0x5A */ { "PHY", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x5B */ { "TCD", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x5C */ { "JMP", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x5D */ { "EOR", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x5E */ { "LSR", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x5F */ { "EOR", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0x60 */ { "RTS", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x61 */ { "ADC", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0x62 */ { "PER", "Relative Long", SizeType::Fixed, 3, 3 },
    /* 0x63 */ { "ADC", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0x64 */ { "STZ", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x65 */ { "ADC", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x66 */ { "ROR", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x67 */ { "ADC", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0x68 */ { "PLA", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x69 */ { "ADC", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0x6A */ { "ROR", "Accumulator", SizeType::Fixed, 1, 1 },
    /* 0x6B */ { "RTL", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x6C */ { "JMP", "Absolute Indirect", SizeType::Fixed, 3, 3 },
    /* 0x6D */ { "ADC", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x6E */ { "ROR", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x6F */ { "ADC", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x70 */ { "BVS", "Relative", SizeType::Fixed, 2, 2 },
    /* 0x71 */ { "ADC", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x72 */ { "ADC", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0x73 */ { "ADC", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x74 */ { "STZ", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x75 */ { "ADC", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x76 */ { "ROR", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x77 */ { "ADC", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x78 */ { "SEI", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x79 */ { "ADC", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0x7A */ { "PLY", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x7B */ { "TDC", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x7C */ { "JMP", "Absolute Indexed Indirect,X", SizeType::Fixed, 3, 3 },
    /* 0x7D */ { "ADC", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x7E */ { "ROR", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x7F */ { "ADC", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0x80 */ { "BRA", "Relative", SizeType::Fixed, 2, 2 },
    /* 0x81 */ { "STA", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0x82 */ { "BRL", "Relative Long", SizeType::Fixed, 3, 3 },
    /* 0x83 */ { "STA", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0x84 */ { "STY", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x85 */ { "STA", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x86 */ { "STX", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0x87 */ { "STA", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0x88 */ { "DEY", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x89 */ { "BIT", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0x8A */ { "TXA", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x8B */ { "PHB", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x8C */ { "STY", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x8D */ { "STA", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x8E */ { "STX", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x8F */ { "STA", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0x90 */ { "BCC", "Relative", SizeType::Fixed, 2, 2 },
    /* 0x91 */ { "STA", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x92 */ { "STA", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0x93 */ { "STA", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x94 */ { "STY", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x95 */ { "STA", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0x96 */ { "STX", "Direct Page Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x97 */ { "STA", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0x98 */ { "TYA", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x99 */ { "STA", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0x9A */ { "TXS", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x9B */ { "TXY", "Implied", SizeType::Fixed, 1, 1 },
    /* 0x9C */ { "STZ", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0x9D */ { "STA", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x9E */ { "STZ", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0x9F */ { "STA", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0xA0 */ { "LDY", "Immediate", SizeType::XDependent, 2, 3 },
    /* 0xA1 */ { "LDA", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0xA2 */ { "LDX", "Immediate", SizeType::XDependent, 2, 3 },
    /* 0xA3 */ { "LDA", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0xA4 */ { "LDY", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xA5 */ { "LDA", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xA6 */ { "LDX", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xA7 */ { "LDA", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0xA8 */ { "TAY", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xA9 */ { "LDA", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0xAA */ { "TAX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xAB */ { "PLB", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xAC */ { "LDY", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xAD */ { "LDA", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xAE */ { "LDX", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xAF */ { "LDA", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0xB0 */ { "BCS", "Relative", SizeType::Fixed, 2, 2 },
    /* 0xB1 */ { "LDA", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xB2 */ { "LDA", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0xB3 */ { "LDA", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xB4 */ { "LDY", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0xB5 */ { "LDA", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0xB6 */ { "LDX", "Direct Page Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xB7 */ { "LDA", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xB8 */ { "CLV", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xB9 */ { "LDA", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0xBA */ { "TSX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xBB */ { "TYX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xBC */ { "LDY", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0xBD */ { "LDA", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0xBE */ { "LDX", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0xBF */ { "LDA", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0xC0 */ { "CPY", "Immediate", SizeType::XDependent, 2, 3 },
    /* 0xC1 */ { "CMP", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0xC2 */ { "REP", "Immediate", SizeType::Fixed, 2, 2 },
    /* 0xC3 */ { "CMP", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0xC4 */ { "CPY", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xC5 */ { "CMP", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xC6 */ { "DEC", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xC7 */ { "CMP", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0xC8 */ { "INY", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xC9 */ { "CMP", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0xCA */ { "DEX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xCB */ { "WAI", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xCC */ { "CPY", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xCD */ { "CMP", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xCE */ { "DEC", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xCF */ { "CMP", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0xD0 */ { "BNE", "Relative", SizeType::Fixed, 2, 2 },
    /* 0xD1 */ { "CMP", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xD2 */ { "CMP", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0xD3 */ { "CMP", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xD4 */ { "PEI", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0xD5 */ { "CMP", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0xD6 */ { "DEC", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0xD7 */ { "CMP", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xD8 */ { "CLD", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xD9 */ { "CMP", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0xDA */ { "PHX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xDB */ { "STP", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xDC */ { "JMP", "Absolute Indirect Long", SizeType::Fixed, 3, 3 },
    /* 0xDD */ { "CMP", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0xDE */ { "DEC", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0xDF */ { "CMP", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
    /* 0xE0 */ { "CPX", "Immediate", SizeType::XDependent, 2, 3 },
    /* 0xE1 */ { "SBC", "Direct Page Indexed Indirect,X", SizeType::Fixed, 2, 2 },
    /* 0xE2 */ { "SEP", "Immediate", SizeType::Fixed, 2, 2 },
    /* 0xE3 */ { "SBC", "Stack Relative", SizeType::Fixed, 2, 2 },
    /* 0xE4 */ { "CPX", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xE5 */ { "SBC", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xE6 */ { "INC", "Direct Page", SizeType::Fixed, 2, 2 },
    /* 0xE7 */ { "SBC", "Direct Page Indirect Long", SizeType::Fixed, 2, 2 },
    /* 0xE8 */ { "INX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xE9 */ { "SBC", "Immediate", SizeType::MDependent, 2, 3 },
    /* 0xEA */ { "NOP", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xEB */ { "XBA", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xEC */ { "CPX", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xED */ { "SBC", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xEE */ { "INC", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xEF */ { "SBC", "Absolute Long", SizeType::Fixed, 4, 4 },
    /* 0xF0 */ { "BEQ", "Relative", SizeType::Fixed, 2, 2 },
    /* 0xF1 */ { "SBC", "Direct Page Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xF2 */ { "SBC", "Direct Page Indirect", SizeType::Fixed, 2, 2 },
    /* 0xF3 */ { "SBC", "Stack Relative Indirect Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xF4 */ { "PEA", "Absolute", SizeType::Fixed, 3, 3 },
    /* 0xF5 */ { "SBC", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0xF6 */ { "INC", "Direct Page Indexed,X", SizeType::Fixed, 2, 2 },
    /* 0xF7 */ { "SBC", "Direct Page Indirect Long Indexed,Y", SizeType::Fixed, 2, 2 },
    /* 0xF8 */ { "SED", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xF9 */ { "SBC", "Absolute Indexed,Y", SizeType::Fixed, 3, 3 },
    /* 0xFA */ { "PLX", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xFB */ { "XCE", "Implied", SizeType::Fixed, 1, 1 },
    /* 0xFC */ { "JSR", "Absolute Indexed Indirect,X", SizeType::Fixed, 3, 3 },
    /* 0xFD */ { "SBC", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0xFE */ { "INC", "Absolute Indexed,X", SizeType::Fixed, 3, 3 },
    /* 0xFF */ { "SBC", "Absolute Long Indexed,X", SizeType::Fixed, 4, 4 },
};