#pragma once

#include <cstdint>
#include <string>

// SPC700 opcode metadata.
//
// The SPC700 uses fixed-size instructions (1, 2, or 3 bytes).
// Unlike the Ricoh 5A22 table, there is no M/X-dependent sizing.

struct SPC700OpCodeInfo
{
    const char* mnemonic;
    const char* addressing_mode;
    uint8_t size;
};

constexpr SPC700OpCodeInfo spc700_opcode_info[256] = {
    /* 0x00 */ { "NOP", "Implied", 1 },
    /* 0x01 */ { "TCALL 0", "Implied", 1 },
    /* 0x02 */ { "SET1", "Direct Page Bit", 2 },
    /* 0x03 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0x04 */ { "OR", "Direct Page", 2 },
    /* 0x05 */ { "OR", "Absolute", 3 },
    /* 0x06 */ { "OR", "Indirect X", 1 },
    /* 0x07 */ { "OR", "Indirect X", 2 },
    /* 0x08 */ { "OR", "Immediate", 2 },
    /* 0x09 */ { "OR", "Direct Page X Direct Page", 2 },
    /* 0x0A */ { "ASL1", "Direct Page Bit", 2 },
    /* 0x0B */ { "ASL", "Direct Page", 2 },
    /* 0x0C */ { "ASL", "Absolute", 3 },
    /* 0x0D */ { "PUSH PSW", "Implied", 1 },
    /* 0x0E */ { "TSET1", "Absolute", 3 },
    /* 0x0F */ { "BRK", "Implied", 1 },

    /* 0x10 */ { "BPL", "Relative", 2 },
    /* 0x11 */ { "TCALL 1", "Implied", 1 },
    /* 0x12 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0x13 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0x14 */ { "OR", "Direct Page X", 2 },
    /* 0x15 */ { "OR", "Absolute X", 3 },
    /* 0x16 */ { "OR", "Absolute Y", 3 },
    /* 0x17 */ { "OR", "Indirect Y", 2 },
    /* 0x18 */ { "OR", "Immediate Direct Page", 3 },
    /* 0x19 */ { "OR", "Direct Page X Direct Page", 2 },
    /* 0x1A */ { "DECW", "Direct Page", 2 },
    /* 0x1B */ { "ASL", "Direct Page X", 2 },
    /* 0x1C */ { "ASL A", "Accumulator", 1 },
    /* 0x1D */ { "DEC X", "Implied", 1 },
    /* 0x1E */ { "CMP X", "Absolute", 3 },
    /* 0x1F */ { "JMP", "Absolute Indexed Indirect", 3 },

    /* 0x20 */ { "CLRP", "Implied", 1 },
    /* 0x21 */ { "TCALL 2", "Implied", 1 },
    /* 0x22 */ { "SET1", "Direct Page Bit", 2 },
    /* 0x23 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0x24 */ { "AND", "Direct Page", 2 },
    /* 0x25 */ { "AND", "Absolute", 3 },
    /* 0x26 */ { "AND", "Indirect X", 1 },
    /* 0x27 */ { "AND", "Indirect X", 2 },
    /* 0x28 */ { "AND", "Immediate", 2 },
    /* 0x29 */ { "AND", "Direct Page X Direct Page", 2 },
    /* 0x2A */ { "ROL1", "Direct Page Bit", 2 },
    /* 0x2B */ { "ROL", "Direct Page", 2 },
    /* 0x2C */ { "ROL", "Absolute", 3 },
    /* 0x2D */ { "PUSH A", "Implied", 1 },
    /* 0x2E */ { "CBNE", "Direct Page Relative", 3 },
    /* 0x2F */ { "BRA", "Relative", 2 },

    /* 0x30 */ { "BMI", "Relative", 2 },
    /* 0x31 */ { "TCALL 3", "Implied", 1 },
    /* 0x32 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0x33 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0x34 */ { "AND", "Direct Page X", 2 },
    /* 0x35 */ { "AND", "Absolute X", 3 },
    /* 0x36 */ { "AND", "Absolute Y", 3 },
    /* 0x37 */ { "AND", "Indirect Y", 2 },
    /* 0x38 */ { "AND", "Immediate Direct Page", 3 },
    /* 0x39 */ { "AND", "Direct Page X Direct Page", 2 },
    /* 0x3A */ { "INCW", "Direct Page", 2 },
    /* 0x3B */ { "ROL", "Direct Page X", 2 },
    /* 0x3C */ { "ROL A", "Accumulator", 1 },
    /* 0x3D */ { "INC X", "Implied", 1 },
    /* 0x3E */ { "CMP X", "Direct Page", 2 },
    /* 0x3F */ { "CALL", "Absolute", 3 },

    /* 0x40 */ { "SETP", "Implied", 1 },
    /* 0x41 */ { "TCALL 4", "Implied", 1 },
    /* 0x42 */ { "SET1", "Direct Page Bit", 2 },
    /* 0x43 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0x44 */ { "EOR", "Direct Page", 2 },
    /* 0x45 */ { "EOR", "Absolute", 3 },
    /* 0x46 */ { "EOR", "Indirect X", 1 },
    /* 0x47 */ { "EOR", "Indirect X", 2 },
    /* 0x48 */ { "EOR", "Immediate", 2 },
    /* 0x49 */ { "EOR", "Direct Page X Direct Page", 2 },
    /* 0x4A */ { "LSR1", "Direct Page Bit", 2 },
    /* 0x4B */ { "LSR", "Direct Page", 2 },
    /* 0x4C */ { "LSR", "Absolute", 3 },
    /* 0x4D */ { "PUSH X", "Implied", 1 },
    /* 0x4E */ { "TCLR1", "Absolute", 3 },
    /* 0x4F */ { "PCALL", "Immediate", 2 },

    /* 0x50 */ { "BVC", "Relative", 2 },
    /* 0x51 */ { "TCALL 5", "Implied", 1 },
    /* 0x52 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0x53 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0x54 */ { "EOR", "Direct Page X", 2 },
    /* 0x55 */ { "EOR", "Absolute X", 3 },
    /* 0x56 */ { "EOR", "Absolute Y", 3 },
    /* 0x57 */ { "EOR", "Indirect Y", 2 },
    /* 0x58 */ { "EOR", "Immediate Direct Page", 3 },
    /* 0x59 */ { "EOR", "Direct Page X Direct Page", 2 },
    /* 0x5A */ { "CMPW YA", "Direct Page", 2 },
    /* 0x5B */ { "LSR", "Direct Page X", 2 },
    /* 0x5C */ { "LSR A", "Accumulator", 1 },
    /* 0x5D */ { "MOV X,A", "Implied", 1 },
    /* 0x5E */ { "CMP X", "Absolute", 3 },
    /* 0x5F */ { "JMP", "Absolute", 3 },

    /* 0x60 */ { "CLRC", "Implied", 1 },
    /* 0x61 */ { "TCALL 6", "Implied", 1 },
    /* 0x62 */ { "SET1", "Direct Page Bit", 2 },
    /* 0x63 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0x64 */ { "CMP", "Direct Page", 2 },
    /* 0x65 */ { "CMP", "Absolute", 3 },
    /* 0x66 */ { "CMP", "Indirect X", 1 },
    /* 0x67 */ { "CMP", "Indirect X", 2 },
    /* 0x68 */ { "CMP", "Immediate", 2 },
    /* 0x69 */ { "CMP", "Direct Page X Direct Page", 2 },
    /* 0x6A */ { "ROR1", "Direct Page Bit", 2 },
    /* 0x6B */ { "ROR", "Direct Page", 2 },
    /* 0x6C */ { "ROR", "Absolute", 3 },
    /* 0x6D */ { "PUSH Y", "Implied", 1 },
    /* 0x6E */ { "DBNZ", "Direct Page Relative", 3 },
    /* 0x6F */ { "RET", "Implied", 1 },

    /* 0x70 */ { "BVS", "Relative", 2 },
    /* 0x71 */ { "TCALL 7", "Implied", 1 },
    /* 0x72 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0x73 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0x74 */ { "CMP", "Direct Page X", 2 },
    /* 0x75 */ { "CMP", "Absolute X", 3 },
    /* 0x76 */ { "CMP", "Absolute Y", 3 },
    /* 0x77 */ { "CMP", "Indirect Y", 2 },
    /* 0x78 */ { "CMP", "Immediate Direct Page", 3 },
    /* 0x79 */ { "CMP", "Direct Page X Direct Page", 2 },
    /* 0x7A */ { "ADDW YA", "Direct Page", 2 },
    /* 0x7B */ { "ROR", "Direct Page X", 2 },
    /* 0x7C */ { "ROR A", "Accumulator", 1 },
    /* 0x7D */ { "MOV A,X", "Implied", 1 },
    /* 0x7E */ { "CMP Y", "Absolute", 3 },
    /* 0x7F */ { "RETI", "Implied", 1 },

    /* 0x80 */ { "SETC", "Implied", 1 },
    /* 0x81 */ { "TCALL 8", "Implied", 1 },
    /* 0x82 */ { "SET1", "Direct Page Bit", 2 },
    /* 0x83 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0x84 */ { "ADC", "Direct Page", 2 },
    /* 0x85 */ { "ADC", "Absolute", 3 },
    /* 0x86 */ { "ADC", "Indirect X", 1 },
    /* 0x87 */ { "ADC", "Indirect X", 2 },
    /* 0x88 */ { "ADC", "Immediate", 2 },
    /* 0x89 */ { "ADC", "Direct Page X Direct Page", 2 },
    /* 0x8A */ { "DEC1", "Direct Page Bit", 2 },
    /* 0x8B */ { "DEC", "Direct Page", 2 },
    /* 0x8C */ { "DEC", "Absolute", 3 },
    /* 0x8D */ { "MOV Y,#imm", "Immediate", 2 },
    /* 0x8E */ { "POP PSW", "Implied", 1 },
    /* 0x8F */ { "MOV DP,#imm", "Direct Page Immediate", 3 },

    /* 0x90 */ { "BCC", "Relative", 2 },
    /* 0x91 */ { "TCALL 9", "Implied", 1 },
    /* 0x92 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0x93 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0x94 */ { "ADC", "Direct Page X", 2 },
    /* 0x95 */ { "ADC", "Absolute X", 3 },
    /* 0x96 */ { "ADC", "Absolute Y", 3 },
    /* 0x97 */ { "ADC", "Indirect Y", 2 },
    /* 0x98 */ { "ADC", "Immediate Direct Page", 3 },
    /* 0x99 */ { "ADC", "Direct Page X Direct Page", 2 },
    /* 0x9A */ { "SUBW YA", "Direct Page", 2 },
    /* 0x9B */ { "DEC", "Direct Page X", 2 },
    /* 0x9C */ { "DEC A", "Accumulator", 1 },
    /* 0x9D */ { "MOV X,SP", "Implied", 1 },
    /* 0x9E */ { "DIV YA,X", "Implied", 1 },
    /* 0x9F */ { "XCN A", "Implied", 1 },

    /* 0xA0 */ { "EI", "Implied", 1 },
    /* 0xA1 */ { "TCALL A", "Implied", 1 },
    /* 0xA2 */ { "SET1", "Direct Page Bit", 2 },
    /* 0xA3 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0xA4 */ { "SBC", "Direct Page", 2 },
    /* 0xA5 */ { "SBC", "Absolute", 3 },
    /* 0xA6 */ { "SBC", "Indirect X", 1 },
    /* 0xA7 */ { "SBC", "Indirect X", 2 },
    /* 0xA8 */ { "SBC", "Immediate", 2 },
    /* 0xA9 */ { "SBC", "Direct Page X Direct Page", 2 },
    /* 0xAA */ { "INC1", "Direct Page Bit", 2 },
    /* 0xAB */ { "INC", "Direct Page", 2 },
    /* 0xAC */ { "INC", "Absolute", 3 },
    /* 0xAD */ { "CMP Y", "Immediate", 2 },
    /* 0xAE */ { "POP A", "Implied", 1 },
    /* 0xAF */ { "MOV (X)+,A", "Indirect X Post-Increment", 1 },

    /* 0xB0 */ { "BCS", "Relative", 2 },
    /* 0xB1 */ { "TCALL B", "Implied", 1 },
    /* 0xB2 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0xB3 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0xB4 */ { "SBC", "Direct Page X", 2 },
    /* 0xB5 */ { "SBC", "Absolute X", 3 },
    /* 0xB6 */ { "SBC", "Absolute Y", 3 },
    /* 0xB7 */ { "SBC", "Indirect Y", 2 },
    /* 0xB8 */ { "SBC", "Immediate Direct Page", 3 },
    /* 0xB9 */ { "SBC", "Direct Page X Direct Page", 2 },
    /* 0xBA */ { "MOVW YA,DP", "Direct Page", 2 },
    /* 0xBB */ { "INC", "Direct Page X", 2 },
    /* 0xBC */ { "INC A", "Accumulator", 1 },
    /* 0xBD */ { "MOV SP,X", "Implied", 1 },
    /* 0xBE */ { "DAS A", "Implied", 1 },
    /* 0xBF */ { "MOV A,(X)+", "Indirect X Post-Increment", 1 },

    /* 0xC0 */ { "DI", "Implied", 1 },
    /* 0xC1 */ { "TCALL C", "Implied", 1 },
    /* 0xC2 */ { "SET1", "Direct Page Bit", 2 },
    /* 0xC3 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0xC4 */ { "MOV", "Direct Page", 2 },
    /* 0xC5 */ { "MOV", "Absolute", 3 },
    /* 0xC6 */ { "MOV", "Indirect X", 1 },
    /* 0xC7 */ { "MOV", "Indirect X", 2 },
    /* 0xC8 */ { "CMP X", "Immediate", 2 },
    /* 0xC9 */ { "MOV", "Absolute", 3 },
    /* 0xCA */ { "MOV1", "Bit", 3 },
    /* 0xCB */ { "MOV", "Direct Page", 2 },
    /* 0xCC */ { "MOV", "Absolute", 3 },
    /* 0xCD */ { "MOV X,#imm", "Immediate", 2 },
    /* 0xCE */ { "POP X", "Implied", 1 },
    /* 0xCF */ { "MUL YA", "Implied", 1 },

    /* 0xD0 */ { "BNE", "Relative", 2 },
    /* 0xD1 */ { "TCALL D", "Implied", 1 },
    /* 0xD2 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0xD3 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0xD4 */ { "MOV", "Direct Page X", 2 },
    /* 0xD5 */ { "MOV", "Absolute X", 3 },
    /* 0xD6 */ { "MOV", "Absolute Y", 3 },
    /* 0xD7 */ { "MOV", "Indirect Y", 2 },
    /* 0xD8 */ { "MOV", "Direct Page", 2 },
    /* 0xD9 */ { "MOV", "Direct Page X", 2 },
    /* 0xDA */ { "MOVW DP,YA", "Direct Page", 2 },
    /* 0xDB */ { "MOV", "Direct Page X", 2 },
    /* 0xDC */ { "DEC Y", "Implied", 1 },
    /* 0xDD */ { "MOV Y,A", "Implied", 1 },
    /* 0xDE */ { "CBNE", "Direct Page X Relative", 3 },
    /* 0xDF */ { "DAA A", "Implied", 1 },

    /* 0xE0 */ { "CLRV", "Implied", 1 },
    /* 0xE1 */ { "TCALL E", "Implied", 1 },
    /* 0xE2 */ { "SET1", "Direct Page Bit", 2 },
    /* 0xE3 */ { "BBS", "Direct Page Bit Relative", 3 },
    /* 0xE4 */ { "MOV A,DP", "Direct Page", 2 },
    /* 0xE5 */ { "MOV A,Absolute", "Absolute", 3 },
    /* 0xE6 */ { "MOV A,(X)", "Indirect X", 1 },
    /* 0xE7 */ { "MOV A,(DP+X)", "Indirect X", 2 },
    /* 0xE8 */ { "MOV A,#imm", "Immediate", 2 },
    /* 0xE9 */ { "MOV X,Absolute", "Absolute", 3 },
    /* 0xEA */ { "NOT1", "Bit", 3 },
    /* 0xEB */ { "MOV Y,DP", "Direct Page", 2 },
    /* 0xEC */ { "MOV Y,Absolute", "Absolute", 3 },
    /* 0xED */ { "NOTC", "Implied", 1 },
    /* 0xEE */ { "POP Y", "Implied", 1 },
    /* 0xEF */ { "SLEEP", "Implied", 1 },

    /* 0xF0 */ { "BEQ", "Relative", 2 },
    /* 0xF1 */ { "TCALL F", "Implied", 1 },
    /* 0xF2 */ { "CLR1", "Direct Page Bit", 2 },
    /* 0xF3 */ { "BBC", "Direct Page Bit Relative", 3 },
    /* 0xF4 */ { "MOV A,DP+X", "Direct Page X", 2 },
    /* 0xF5 */ { "MOV A,Absolute+X", "Absolute X", 3 },
    /* 0xF6 */ { "MOV A,Absolute+Y", "Absolute Y", 3 },
    /* 0xF7 */ { "MOV A,(DP)+Y", "Indirect Y", 2 },
    /* 0xF8 */ { "MOV X,DP", "Direct Page", 2 },
    /* 0xF9 */ { "MOV X,DP+Y", "Direct Page Y", 2 },
    /* 0xFA */ { "MOV DP,DP", "Direct Page", 3 },
    /* 0xFB */ { "MOV Y,DP+X", "Direct Page X", 2 },
    /* 0xFC */ { "INC Y", "Implied", 1 },
    /* 0xFD */ { "MOV Y,A", "Implied", 1 },
    /* 0xFE */ { "DBNZ Y", "Relative", 2 },
    /* 0xFF */ { "STOP", "Implied", 1 },
};